spring:
  application:
    name: binance-finance-tracker

  datasource:
    url: jdbc:postgresql://localhost/mydb
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate #update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

binance:
  api:
    key: ${BINANCE_API_KEY}
  secret:
    key: ${BINANCE_SECRET_KEY}