spring:
  application:
    name: binance-finance-tracker

  flyway:
    url: jdbc:postgresql://localhost/mydb
    user: admin
    password: secret
    schemas: public
    enabled: true
    locations:
      classpath: db/migrations
    baselineOnMigrate: true


  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000

  datasource:
    url: jdbc:postgresql://localhost/mydb
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate #update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false

binance:
  api:
    key: ${BINANCE_API_KEY}
  secret:
    key: ${BINANCE_SECRET_KEY}